version: '3.8'
services:
  web:
    build: .
    ports:
      - "7000:7000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_HOST=192.168.1.30
      - DATABASE_USER=cola
      - DATABASE_PASSWORD=sabritas
      - DATABASE_DB=cola
    volumes:
      - /copias:/app/copias
